spring:
 security:
   user:
     name: dungdt
     password: 123456

spring:
 profiles: peer2
eureka:
 instance:
   hostname: peer2
 client:
   serviceUrl:
#      defaultZone: http://dungdt:123456@peer1:8761/eureka/,http://dungdt:123456@peer3:8763/eureka/
     defaultZone: http://dungdt:123456@peer1:8761/eureka/
server:
 port: ${PORT:8762}