spring:
 security:
   user:
     name: dungdt
     password: 123456

spring:
 profiles: peer1
eureka:
 instance:
   hostname: peer1
 client:
   serviceUrl:
#      defaultZone: http://dungdt:123456@peer2:8762/eureka/,http://dungdt:123456@peer3:8763/eureka/
     defaultZone: http://dungdt:123456@peer2:8762/eureka/
server:
 port: ${PORT:8761}